import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import LenisProvider from "@/components/common/LenisProvider";
import TopBar from "@/components/common/TopBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen scroll-smooth overflow-y-auto`}
        style={{ scrollBehavior: "smooth" }}
      >
        <LenisProvider>
          <div className="hidden sm:block">
            <TopBar />
          </div>
          <Navbar />
          <div className="flex-1 flex flex-col">{children}</div>
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
